<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ProductNutrition;

class ProductNutritionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nutritions = [
        [
            'name' => 'Almond Milk',
            'short_description' => 'Plant-based milk from almonds and water; popular dairy alternative. Typically fortified with calcium and vitamins.',
            'calories' => 15,
            'protein' => 0.5,
            'carbs' => 0.3,
            'sugar' => 0.0,
            'fiber' => 0.2,
            'fat' => 1.1,
            'saturated_fat' => 0.1,
            'monounsaturated_fat' => 0.7,
            'polyunsaturated_fat' => 0.3,
            'salt' => 60,
            'vitamins_minerals' => 'Calcium, Vitamin D, B12, E (often fortified)',
            'serving_size' => '200ml glass',
            'allergens' => 'Almond (tree nuts)',
            'common_uses' => 'Drinks, cereals, smoothies, coffee, baking',
        ],
        [
            'name' => 'Avocado',
            'short_description' => 'Creamy, nutrient-dense fruit native to Central America, prized for its healthy fats and versatility.',
            'calories' => 160,
            'protein' => 2.0,
            'carbs' => 8.5,
            'sugar' => 0.7,
            'fiber' => 6.7,
            'fat' => 15.0,
            'saturated_fat' => 2.1,
            'monounsaturated_fat' => 9.8,
            'polyunsaturated_fat' => 1.8,
            'salt' => 7,
            'vitamins_minerals' => 'Potassium, Folate, Vitamin K, Vitamin C, Vitamin E',
            'serving_size' => '½ medium avocado (~70g)',
            'allergens' => 'Rare; latex-fruit syndrome possible',
            'common_uses' => 'Salads, toast, guacamole, sushi, smoothies',
        ],
        [
            'name' => 'Blueberries',
            'short_description' => 'Sweet, antioxidant-rich berries. Commonly grown in North America/Europe.',
            'calories' => 57,
            'protein' => 0.7,
            'carbs' => 14.5,
            'sugar' => 10.0,
            'fiber' => 2.4,
            'fat' => 0.3,
            'saturated_fat' => 0.0,
            'monounsaturated_fat' => null,
            'polyunsaturated_fat' => null,
            'salt' => 1,
            'vitamins_minerals' => 'Vitamin C, Vitamin K, Manganese, Vitamin A, E',
            'serving_size' => '80g (handful)',
            'allergens' => 'Very rare; possible oral allergy syndrome',
            'common_uses' => 'Snacking, cereal, yogurt, baking, smoothies',
        ],
        [
            'name' => 'Broccoli',
            'short_description' => 'Green cruciferous vegetable, rich in vitamin C and fiber. Used raw or cooked.',
            'calories' => 34,
            'protein' => 2.8,
            'carbs' => 6.6,
            'sugar' => 1.7,
            'fiber' => 2.6,
            'fat' => 0.4,
            'saturated_fat' => 0.1,
            'monounsaturated_fat' => null,
            'polyunsaturated_fat' => null,
            'salt' => 33,
            'vitamins_minerals' => 'Vitamin C, Vitamin K, Folate, Potassium',
            'serving_size' => '85g (1 cup)',
            'allergens' => 'Rare; cruciferous allergy possible',
            'common_uses' => 'Steamed, stir-fries, salads, soups, raw',
        ],
        [
            'name' => 'Brown Eggs',
            'short_description' => 'Large chicken eggs (brown vs white nutritionally identical). Excellent protein source with vitamins.',
            'calories' => 143,
            'protein' => 13.0,
            'carbs' => 1.1,
            'sugar' => 0.4,
            'fiber' => 0.0,
            'fat' => 10.0,
            'saturated_fat' => 3.1,
            'monounsaturated_fat' => 3.6,
            'polyunsaturated_fat' => 1.9,
            'salt' => 140,
            'vitamins_minerals' => 'Vitamin B12, D, A, Choline, Selenium',
            'serving_size' => '1 egg (~63g)',
            'allergens' => 'Egg',
            'common_uses' => 'Boiled, scrambled, omelets, baking, etc.',
        ],
            [
                'name' => 'Butter',
                'short_description' => 'Dairy fat spread. High in fat and fat-soluble vitamins (A, D, E, K).',
                'calories' => 717,
                'protein' => 0.9,
                'carbs' => 0.1,
                'sugar' => 0.1,
                'fiber' => 0.0,
                'fat' => 81.0,
                'saturated_fat' => 51.0,
                'monounsaturated_fat' => 21.0,
                'polyunsaturated_fat' => 3.0,
                'salt' => 11,
                'vitamins_minerals' => 'Vitamin A, D, E, K2',
                'serving_size' => '10g (1 tbsp)',
                'allergens' => 'Milk (dairy)',
                'common_uses' => 'Spreads, baking, frying, sauces',
            ],
            [
                'name' => 'Capers',
                'short_description' => 'Small pickled flower buds, very salty and tangy, used in Mediterranean dishes.',
                'calories' => 23,
                'protein' => 2.4,
                'carbs' => 4.9,
                'sugar' => 0.4,
                'fiber' => 3.2,
                'fat' => 0.9,
                'saturated_fat' => 0.2,
                'monounsaturated_fat' => 0.1,
                'polyunsaturated_fat' => 0.3,
                'salt' => 2500,
                'vitamins_minerals' => 'Vitamin K, Iron, Copper, Magnesium',
                'serving_size' => '8g (1 tbsp)',
                'allergens' => 'None specifically; possible cross-contact',
                'common_uses' => 'Salads, pasta, fish, sauces, tapenade',
            ],
            [
                'name' => 'Carrots',
                'short_description' => 'Crunchy orange root vegetable, rich in beta-carotene and fiber.',
                'calories' => 41,
                'protein' => 0.9,
                'carbs' => 9.6,
                'sugar' => 4.7,
                'fiber' => 2.8,
                'fat' => 0.2,
                'saturated_fat' => 0.0,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 69,
                'vitamins_minerals' => 'Vitamin A (beta-carotene), K1, Potassium, Biotin',
                'serving_size' => '61g (1 medium)',
                'allergens' => 'Rare (oral allergy possible)',
                'common_uses' => 'Raw snacks, salads, soups, roasting, juicing',
            ],
            [
                'name' => 'Cashew Milk',
                'short_description' => 'Creamy dairy alternative from cashews. Used like other nut milks.',
                'calories' => 15,
                'protein' => 0.5,
                'carbs' => 1.5,
                'sugar' => 0.2,
                'fiber' => 0.1,
                'fat' => 0.9,
                'saturated_fat' => 0.1,
                'monounsaturated_fat' => 0.5,
                'polyunsaturated_fat' => 0.2,
                'salt' => 120,
                'vitamins_minerals' => 'Calcium, Vitamin D, E, B12 (fortified)',
                'serving_size' => '200ml glass',
                'allergens' => 'Cashew (tree nuts)',
                'common_uses' => 'Drinks, cereals, smoothies, coffee, baking',
            ],
            [
                'name' => 'Celery',
                'short_description' => 'Pale green crunchy stalk, high water content. Provides vitamin K and dietary fiber.',
                'calories' => 16,
                'protein' => 0.7,
                'carbs' => 3.0,
                'sugar' => 1.3,
                'fiber' => 1.6,
                'fat' => 0.2,
                'saturated_fat' => 0.04,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 80,
                'vitamins_minerals' => 'Vitamin K, Folate, Potassium, Vitamin C',
                'serving_size' => '40g (1 medium stalk)',
                'allergens' => 'Celery',
                'common_uses' => 'Raw snacks, salads, soups, stews, stir-fries',
            ],
            [
                'name' => 'Chicken Breast',
                'short_description' => 'Lean boneless, skinless chicken. High protein, low fat.',
                'calories' => 110,
                'protein' => 23.0,
                'carbs' => 0.0,
                'sugar' => 0.0,
                'fiber' => 0.0,
                'fat' => 1.2,
                'saturated_fat' => 0.3,
                'monounsaturated_fat' => 0.3,
                'polyunsaturated_fat' => 0.3,
                'salt' => 45,
                'vitamins_minerals' => 'Niacin (B3), Vitamin B6, Phosphorus, Selenium',
                'serving_size' => '120–150g (1 breast)',
                'allergens' => 'None (rare poultry allergy possible)',
                'common_uses' => 'Grilling, baking, stir-fries, salads, soups',
            ],
            [
                'name' => 'Coconut',
                'short_description' => 'Tropical fruit with high fat. White edible flesh inside the shell.',
                'calories' => 354,
                'protein' => 3.3,
                'carbs' => 15.2,
                'sugar' => 6.2,
                'fiber' => 9.0,
                'fat' => 33.5,
                'saturated_fat' => 29.7,
                'monounsaturated_fat' => 1.4,
                'polyunsaturated_fat' => 0.4,
                'salt' => 20,
                'vitamins_minerals' => 'Manganese, Copper, Selenium, Iron, Potassium',
                'serving_size' => '30g shredded',
                'allergens' => 'Coconut (tree nut–classified in US)',
                'common_uses' => 'Curries, desserts, baking, smoothies, snacks',
            ],
            [
                'name' => 'Coconut Milk',
                'short_description' => 'Thick dairy-free milk from blended coconut flesh. Common in Asian/Caribbean cuisine.',
                'calories' => 230,
                'protein' => 2.3,
                'carbs' => 5.5,
                'sugar' => 3.3,
                'fiber' => 2.2,
                'fat' => 24.0,
                'saturated_fat' => 21.0,
                'monounsaturated_fat' => 1.0,
                'polyunsaturated_fat' => 0.3,
                'salt' => 15,
                'vitamins_minerals' => 'Manganese, Copper, Iron, Magnesium',
                'serving_size' => '60ml (1/4 cup)',
                'allergens' => 'Rare (coconut); check for sulfites',
                'common_uses' => 'Curries, soups, smoothies, sauces, desserts',
            ],
            [
                'name' => 'Coconut Yogurt',
                'short_description' => 'Fermented coconut milk product. Dairy-free yogurt alternative.',
                'calories' => 100,
                'protein' => 1.0,
                'carbs' => 5.0,
                'sugar' => 2.0,
                'fiber' => 1.0,
                'fat' => 8.0,
                'saturated_fat' => 7.0,
                'monounsaturated_fat' => 0.7,
                'polyunsaturated_fat' => 0.2,
                'salt' => 10,
                'vitamins_minerals' => 'Calcium, Vitamin B12 (if fortified), live cultures',
                'serving_size' => '125g (1 small cup)',
                'allergens' => 'Coconut',
                'common_uses' => 'Breakfast bowls, smoothies, desserts',
            ],
            [
                'name' => 'Cow Milk',
                'short_description' => 'Traditional dairy milk (~3.3% fat). Rich in calcium and protein.',
                'calories' => 61,
                'protein' => 3.2,
                'carbs' => 4.8,
                'sugar' => 4.8,
                'fiber' => 0.0,
                'fat' => 3.3,
                'saturated_fat' => 2.1,
                'monounsaturated_fat' => 0.8,
                'polyunsaturated_fat' => 0.1,
                'salt' => 44,
                'vitamins_minerals' => 'Calcium, B12, Riboflavin, Phosphorus, Vitamin D (if fortified)',
                'serving_size' => '200ml',
                'allergens' => 'Milk (dairy, contains lactose and milk proteins)',
                'common_uses' => 'Drinking, cereals, coffee, baking, sauces',
            ],
            [
                'name' => 'Cucumber',
                'short_description' => 'High-water-content green vegetable, very low calorie.',
                'calories' => 16,
                'protein' => 0.7,
                'carbs' => 3.6,
                'sugar' => 1.7,
                'fiber' => 0.5,
                'fat' => 0.1,
                'saturated_fat' => 0.0,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 2,
                'vitamins_minerals' => 'Vitamin K, Vitamin C, Potassium',
                'serving_size' => '100g (1/2 cucumber)',
                'allergens' => 'Rare; occasional oral allergy in sensitive individuals',
                'common_uses' => 'Salads, sandwiches, tzatziki, pickling, raw snack',
            ],
            [
                'name' => 'Feta Cheese',
                'short_description' => 'Greek-style brined cheese (sheep/goat milk). Tangy, salty, crumbly.',
                'calories' => 264,
                'protein' => 14.0,
                'carbs' => 4.1,
                'sugar' => 4.1,
                'fiber' => 0.0,
                'fat' => 21.0,
                'saturated_fat' => 14.0,
                'monounsaturated_fat' => 5.0,
                'polyunsaturated_fat' => 1.2,
                'salt' => 917,
                'vitamins_minerals' => 'Calcium, Phosphorus, B12, Riboflavin',
                'serving_size' => '30g',
                'allergens' => 'Milk (dairy)',
                'common_uses' => 'Salads, sandwiches, pastries, omelets',
            ],
            [
                'name' => 'Fresh Dill',
                'short_description' => 'Fragrant herb (feathery leaves) used in European/Middle Eastern cuisine.',
                'calories' => 43,
                'protein' => 3.5,
                'carbs' => 7.0,
                'sugar' => 0.0,
                'fiber' => 2.1,
                'fat' => 1.1,
                'saturated_fat' => 0.1,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 61,
                'vitamins_minerals' => 'Vitamin C, Vitamin A, Manganese, Iron',
                'serving_size' => '5g (1 tbsp chopped)',
                'allergens' => 'Rare',
                'common_uses' => 'Garnishes, dips, fish dishes, soups, pickling',
            ],
            [
                'name' => 'Fresh Parsley',
                'short_description' => 'Leafy herb used globally (flat-leaf or curly). Fresh flavor.',
                'calories' => 36,
                'protein' => 3.0,
                'carbs' => 6.0,
                'sugar' => 0.9,
                'fiber' => 3.3,
                'fat' => 0.8,
                'saturated_fat' => 0.1,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 56,
                'vitamins_minerals' => 'Vitamin K, Vitamin C, Vitamin A, Folate, Iron',
                'serving_size' => '5g (1 tbsp chopped)',
                'allergens' => 'Rare',
                'common_uses' => 'Garnish, salads, tabbouleh, sauces, soups',
            ],
            [
                'name' => 'Green Grapes',
                'short_description' => 'Seedless table grapes. Sweet, crispy.',
                'calories' => 69,
                'protein' => 0.7,
                'carbs' => 18.0,
                'sugar' => 16.0,
                'fiber' => 0.9,
                'fat' => 0.2,
                'saturated_fat' => 0.0,
                'monounsaturated_fat' => null,
                'polyunsaturated_fat' => null,
                'salt' => 2,
                'vitamins_minerals' => 'Vitamin C, Vitamin K, Potassium, Copper',
                'serving_size' => '80g (1 cup)',
                'allergens' => 'Rare (pollen allergies)',
                'common_uses' => 'Snacking, fruit salads, desserts, juice, cheese boards',
            ],
            [
                'name' => 'Hazelnut Milk',
                'short_description' => 'Dairy alternative from hazelnuts. Nutty flavor.',
                'calories' => 29,
                'protein' => 0.4,
                'carbs' => 0.6,
                'sugar' => 0.3,
                'fiber' => 0.1,
                'fat' => 2.8,
                'saturated_fat' => 0.2,
                'monounsaturated_fat' => 2.2,
                'polyunsaturated_fat' => 0.4,
                'salt' => 90,
                'vitamins_minerals' => 'Calcium, Vitamin D, Vitamin E, Vitamin B12 (fortified)',
                'serving_size' => '200ml',
                'allergens' => 'Hazelnuts (tree nuts)',
                'common_uses' => 'Drinks, cereal, smoothies, coffee, baking',
            ],
            [
                'name' => 'Hot Sauce',
                'short_description' => 'Spicy condiment of chili peppers, vinegar, salt. Very low calorie, very high sodium.',
                'calories' => 30,
                'protein' => 1,
                'carbs' => 5,
                'sugar' => 2,
                'fiber' => 1,
                'fat' => 0,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1200,
                'vitamins_minerals' => 'Vitamin C, Capsaicin',
                'serving_size' => '5g (1 tsp)',
                'allergens' => 'Rare (mustard, other additives possible)',
                'common_uses' => 'Adds heat/flavor to meats, eggs, soups, sauces, marinades',
            ],
            [
                'name' => 'Hummus',
                'short_description' => 'Chickpea-tahini dip. High fiber and protein from chickpeas and sesame.',
                'calories' => 166,
                'protein' => 7.9,
                'carbs' => 14.3,
                'sugar' => 0.3,
                'fiber' => 6.0,
                'fat' => 9.6,
                'saturated_fat' => 1.4,
                'monounsaturated_fat' => 4.0,
                'polyunsaturated_fat' => 2.7,
                'salt' => 379,
                'vitamins_minerals' => 'Folate, Iron, Manganese, Copper, Phosphorus',
                'serving_size' => '50g (~3 tbsp)',
                'allergens' => 'Sesame (tahini); may contain traces of other allergens',
                'common_uses' => 'Dip, spread, wraps/sandwiches, salads, Mediterranean dishes',
            ],
            [
                'name' => 'Lemon',
                'short_description' => 'Citrus fruit; tart juice and zest used in foods and drinks worldwide.',
                'calories' => 29,
                'protein' => 1.1,
                'carbs' => 9.3,
                'sugar' => 2.5,
                'fiber' => 2.8,
                'fat' => 0.3,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 2,
                'vitamins_minerals' => 'Vitamin C (53mg), Vitamin B6, Potassium',
                'serving_size' => '58g (1 medium lemon)',
                'allergens' => 'Rare (citrus allergy)',
                'common_uses' => 'Juice, zest, desserts, drinks, marinades',
            ],
            [
                'name' => 'Lemon Juice',
                'short_description' => 'Concentrated citrus juice (tart), used in cooking and drinks.',
                'calories' => 22,
                'protein' => 0.4,
                'carbs' => 6.9,
                'sugar' => 2.5,
                'fiber' => 0.3,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1,
                'vitamins_minerals' => 'Vitamin C (38mg), Potassium',
                'serving_size' => '15ml (1 tbsp)',
                'allergens' => 'None (rare citrus)',
                'common_uses' => 'Marinades, dressings, baking, cocktails, tea',
            ],
            [
                'name' => 'Marinated Artichokes',
                'short_description' => 'Artichoke hearts marinated in oil/vinegar. Mediterranean antipasti item.',
                'calories' => 124,
                'protein' => 2.8,
                'carbs' => 5.2,
                'sugar' => 1.0,
                'fiber' => 4.0,
                'fat' => 9.2,
                'saturated_fat' => 1.1,
                'monounsaturated_fat' => 6.2,
                'polyunsaturated_fat' => 1.3,
                'salt' => 1100,
                'vitamins_minerals' => 'Vitamin C, Folate, Iron, Magnesium',
                'serving_size' => '30g (~3–4 pieces)',
                'allergens' => 'May contain celery, mustard, sulfites',
                'common_uses' => 'Antipasti, salads, pizza topping, pasta, charcuterie boards',
            ],
            [
                'name' => 'Mayonnaise Jar Spoon',
                'short_description' => 'Emulsified oil and egg condiment. Very high in fat.',
                'calories' => 680,
                'protein' => 1,
                'carbs' => 0.6,
                'sugar' => 0.6,
                'fiber' => 0,
                'fat' => 75,
                'saturated_fat' => 11,
                'monounsaturated_fat' => 44,
                'polyunsaturated_fat' => 18,
                'salt' => 600,
                'vitamins_minerals' => 'Vitamin E, Vitamin K, B vitamins',
                'serving_size' => '15g (1 tbsp)',
                'allergens' => 'Eggs (and sometimes mustard)',
                'common_uses' => 'Spread (sandwiches, burgers), dressing base, dips, sauces, coleslaw',
            ],
            [
                'name' => 'Mushrooms',
                'short_description' => 'Mild fresh mushrooms, widely used in cooking.',
                'calories' => 22,
                'protein' => 3.1,
                'carbs' => 3.3,
                'sugar' => 2.0,
                'fiber' => 1.0,
                'fat' => 0.3,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 5,
                'vitamins_minerals' => 'Vitamin D (if exposed to light), B vitamins (riboflavin, niacin), selenium, copper',
                'serving_size' => '80g (≈1 cup sliced)',
                'allergens' => 'Rare (fungal/mold allergy possible)',
                'common_uses' => 'Salads, stir-fries, pizza topping, pasta, soups, sautéing',
            ],
            [
                'name' => 'Mustard Jar',
                'short_description' => 'Pungent ground mustard seed condiment with vinegar. Low calorie, high sodium and fiber.',
                'calories' => 66,
                'protein' => 3.6,
                'carbs' => 5.8,
                'sugar' => 0.9,
                'fiber' => 4.0,
                'fat' => 4.0,
                'saturated_fat' => 0.2,
                'monounsaturated_fat' => 2.5,
                'polyunsaturated_fat' => 0.5,
                'salt' => 1200,
                'vitamins_minerals' => 'Selenium, Magnesium, Iron, Phosphorus',
                'serving_size' => '10g (1 tsp)',
                'allergens' => 'Mustard seed',
                'common_uses' => 'Sandwiches, sausages, vinaigrettes, marinades, sauces',
            ],
            [
                'name' => 'Oat Milk',
                'short_description' => 'Plant-based milk made from oats. Popular dairy alternative.',
                'calories' => 43,
                'protein' => 1,
                'carbs' => 6.7,
                'sugar' => 4,
                'fiber' => 0.8,
                'fat' => 1.5,
                'saturated_fat' => 0.2,
                'monounsaturated_fat' => 0.6,
                'polyunsaturated_fat' => 0.7,
                'salt' => 100,
                'vitamins_minerals' => 'Calcium, Vitamin D, Vitamin B12, Riboflavin (fortified)',
                'serving_size' => '200ml',
                'allergens' => 'Oats (gluten if not certified GF); may contain nut/soy cross-contact',
                'common_uses' => 'Coffee, cereal, smoothies, baking, drinking',
            ],
            [
                'name' => 'Olives',
                'short_description' => 'Pickled olive fruit; very high in healthy fats and salt.',
                'calories' => 145,
                'protein' => 1.0,
                'carbs' => 3.8,
                'sugar' => 0,
                'fiber' => 3.3,
                'fat' => 15,
                'saturated_fat' => 2,
                'monounsaturated_fat' => 11,
                'polyunsaturated_fat' => 1.4,
                'salt' => 1556,
                'vitamins_minerals' => 'Vitamin E, Iron, Copper',
                'serving_size' => '15g (~5 olives)',
                'allergens' => 'Rare; possible processing contact with pits or nuts',
                'common_uses' => 'Salads, antipasti, pizza, tapenade, snacks',
            ],
            [
                'name' => 'Parmesan',
                'short_description' => 'Hard, aged Italian cheese (cow’s milk). Nutty, granular.',
                'calories' => 431,
                'protein' => 38,
                'carbs' => 4.1,
                'sugar' => 0,
                'fiber' => 0,
                'fat' => 29,
                'saturated_fat' => 18,
                'monounsaturated_fat' => 9,
                'polyunsaturated_fat' => 0.9,
                'salt' => 1600,
                'vitamins_minerals' => 'Calcium, Phosphorus, Vitamin A, B12',
                'serving_size' => '20g (≈2 tbsp grated)',
                'allergens' => 'Milk (dairy)',
                'common_uses' => 'Shaved or grated on pasta, risotto, salads; snack',
            ],
            [
                'name' => 'Pesto Jar Spoon',
                'short_description' => 'Italian basil sauce (oil, pine nuts, Parmesan, garlic).',
                'calories' => 450,
                'protein' => 5,
                'carbs' => 7,
                'sugar' => 1.7,
                'fiber' => 1.4,
                'fat' => 45,
                'saturated_fat' => 6,
                'monounsaturated_fat' => 32,
                'polyunsaturated_fat' => 6,
                'salt' => 1400,
                'vitamins_minerals' => 'Vitamin E, Vitamin K, Calcium, Iron',
                'serving_size' => '20g (≈1 tbsp)',
                'allergens' => 'Pine nuts (tree nuts), milk (Parmesan), may contain other nuts',
                'common_uses' => 'Pasta sauces, sandwiches, dressings, marinades, pizza',
            ],
            [
                'name' => 'Pickle Jar',
                'short_description' => 'Vinegar-brined cucumbers. Very low calorie, very high sodium.',
                'calories' => 12,
                'protein' => 0.5,
                'carbs' => 2.3,
                'sugar' => 1.1,
                'fiber' => 1.2,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1200,
                'vitamins_minerals' => 'Vitamin K, Potassium (trace)',
                'serving_size' => '30g (~2–3 slices)',
                'allergens' => 'May contain mustard or sulfites',
                'common_uses' => 'Sandwiches, burgers, salads, snack',
            ],
            [
                'name' => 'Raspberries',
                'short_description' => 'Small tart red berries high in fiber and antioxidants.',
                'calories' => 52,
                'protein' => 1.2,
                'carbs' => 12,
                'sugar' => 4.4,
                'fiber' => 6.5,
                'fat' => 0.7,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1,
                'vitamins_minerals' => 'Vitamin C, Manganese, Vitamin K',
                'serving_size' => '80g (~1 cup)',
                'allergens' => 'Rare (oral allergy possible)',
                'common_uses' => 'Snacking, desserts, yogurt, smoothies, baking',
            ],
            [
                'name' => 'Ravioli',
                'short_description' => 'Italian filled pasta (ricotta/herb).',
                'calories' => 220,
                'protein' => 8,
                'carbs' => 33,
                'sugar' => 1,
                'fiber' => 1.8,
                'fat' => 6,
                'saturated_fat' => 2.5,
                'monounsaturated_fat' => 2,
                'polyunsaturated_fat' => 0.8,
                'salt' => 400,
                'vitamins_minerals' => 'Calcium, Iron, Vitamin A',
                'serving_size' => '125g (10 pieces)',
                'allergens' => 'Wheat (gluten), milk (cheese), eggs (pasta)',
                'common_uses' => 'Boil and sauce, bake, in soups',
            ],
            [
                'name' => 'Raw Salmon',
                'short_description' => 'Pink-fleshed oily fish, high in omega-3s.',
                'calories' => 208,
                'protein' => 20,
                'carbs' => 0,
                'sugar' => 0,
                'fiber' => 0,
                'fat' => 13,
                'saturated_fat' => 3.1,
                'monounsaturated_fat' => 3.8,
                'polyunsaturated_fat' => 3.9,
                'salt' => 59,
                'vitamins_minerals' => 'Vitamin D, B12, Selenium, Potassium',
                'serving_size' => '100g fillet',
                'allergens' => 'Fish',
                'common_uses' => 'Sushi, sashimi, grilling, baking, pan-searing',
            ],
            [
                'name' => 'Red Apple',
                'short_description' => 'Crisp sweet-tart fruit with red skin.',
                'calories' => 52,
                'protein' => 0.3,
                'carbs' => 14,
                'sugar' => 10,
                'fiber' => 2.4,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1,
                'vitamins_minerals' => 'Vitamin C, Potassium',
                'serving_size' => '150g (1 medium apple)',
                'allergens' => 'Rare (pollen-fruit syndrome)',
                'common_uses' => 'Snacking, salads, baking, sauces',
            ],
            [
                'name' => 'Red Fruit Jam',
                'short_description' => 'Sweet fruit preserve (berries, sugar, pectin).',
                'calories' => 250,
                'protein' => 0.4,
                'carbs' => 61,
                'sugar' => 54,
                'fiber' => 1.5,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 20,
                'vitamins_minerals' => 'Small amounts of vitamin C, potassium from fruit',
                'serving_size' => '20g (1 tbsp)',
                'allergens' => 'Rare (depending on brand, maybe nuts)',
                'common_uses' => 'Spreads on toast, baking, yogurt topping, desserts',
            ],
            [
                'name' => 'Red Onion',
                'short_description' => 'Purple-skinned onion, milder/sweeter flavor.',
                'calories' => 40,
                'protein' => 1.1,
                'carbs' => 9.3,
                'sugar' => 4.2,
                'fiber' => 1.7,
                'fat' => 0.1,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 4,
                'vitamins_minerals' => 'Vitamin C, B6, Folate, Potassium',
                'serving_size' => '80g (1 medium)',
                'allergens' => 'Rare (onion allergy or cross-reactive pollen)',
                'common_uses' => 'Salads, sandwiches, salsas, pickles',
            ],
            [
                'name' => 'Red Pepper',
                'short_description' => 'Bright red bell pepper. High in vitamin C.',
                'calories' => 31,
                'protein' => 1,
                'carbs' => 6,
                'sugar' => 4.2,
                'fiber' => 2.1,
                'fat' => 0.3,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 4,
                'vitamins_minerals' => 'Vitamin C, Vitamin A, Vitamin B6, Folate',
                'serving_size' => '85g (1 small pepper)',
                'allergens' => 'Rare',
                'common_uses' => 'Raw (snacking, salads), grilling, stir-fries, roasting',
            ],
            [
                'name' => 'Salsa Sauce',
                'short_description' => 'Chunky tomato-pepper condiment (Mexican style).',
                'calories' => 30,
                'protein' => 1.2,
                'carbs' => 6.0,
                'sugar' => 3.5,
                'fiber' => 1.8,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 650,
                'vitamins_minerals' => 'Vitamin C, Vitamin A, Potassium',
                'serving_size' => '30g (≈2 tbsp)',
                'allergens' => 'Rare (check for extra flavorings)',
                'common_uses' => 'Dip (chips), toppings for nachos, tacos, eggs, grilled meats',
            ],
            [
                'name' => 'Sliced Cheddar',
                'short_description' => 'Firm sharp cheese (often orange-colored) pre-sliced.',
                'calories' => 403,
                'protein' => 25,
                'carbs' => 1.3,
                'sugar' => 0.5,
                'fiber' => 0,
                'fat' => 33,
                'saturated_fat' => 19,
                'monounsaturated_fat' => 9,
                'polyunsaturated_fat' => 1,
                'salt' => 620,
                'vitamins_minerals' => 'Calcium, Vitamin A, Vitamin B12',
                'serving_size' => '20g (1–2 slices)',
                'allergens' => 'Milk (dairy)',
                'common_uses' => 'Sandwiches, burgers, snacks, melting',
            ],
            [
                'name' => 'Sliced Mozzarella',
                'short_description' => 'Soft, mild white cheese (cow’s or buffalo’s milk).',
                'calories' => 280,
                'protein' => 18,
                'carbs' => 3,
                'sugar' => 1,
                'fiber' => 0,
                'fat' => 21,
                'saturated_fat' => 13,
                'monounsaturated_fat' => 6,
                'polyunsaturated_fat' => 0.6,
                'salt' => 400,
                'vitamins_minerals' => 'Calcium, B12, Phosphorus',
                'serving_size' => '28g (2–3 slices)',
                'allergens' => 'Milk (dairy)',
                'common_uses' => 'Caprese salad, pizza, sandwiches, melting',
            ],
            [
                'name' => 'Smoked Salmon',
                'short_description' => 'Thinly sliced cured cold-smoked salmon (ready-to-eat).',
                'calories' => 117,
                'protein' => 18,
                'carbs' => 0,
                'sugar' => 0,
                'fiber' => 0,
                'fat' => 4.3,
                'saturated_fat' => 0.9,
                'monounsaturated_fat' => 1.5,
                'polyunsaturated_fat' => 1.4,
                'salt' => 700,
                'vitamins_minerals' => 'Vitamin D, B12, Selenium, Phosphorus',
                'serving_size' => '30g (≈2 slices)',
                'allergens' => 'Fish',
                'common_uses' => 'Bagels with cream cheese, salads, canapés, sandwiches, sushi',
            ],
            [
                'name' => 'Spinach',
                'short_description' => 'Leafy green vegetable, very rich in vitamins/minerals.',
                'calories' => 23,
                'protein' => 2.9,
                'carbs' => 3.6,
                'sugar' => 0.4,
                'fiber' => 2.2,
                'fat' => 0.4,
                'saturated_fat' => 0.1,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 79,
                'vitamins_minerals' => 'Vitamin K, Vitamin A, Vitamin C, Folate, Iron, Magnesium',
                'serving_size' => '30g (~1 cup raw)',
                'allergens' => 'Rare (oral allergy possible)',
                'common_uses' => 'Salads, smoothies, stir-fries, quiches, omelets',
            ],
            [
                'name' => 'Strawberries',
                'short_description' => 'Sweet red berries, high in vitamin C and antioxidants.',
                'calories' => 32,
                'protein' => 0.7,
                'carbs' => 7.7,
                'sugar' => 4.9,
                'fiber' => 2.0,
                'fat' => 0.3,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 1,
                'vitamins_minerals' => 'Vitamin C, Manganese, Folate',
                'serving_size' => '80g (1 cup halved)',
                'allergens' => 'Rare (oral allergy)',
                'common_uses' => 'Snacking, desserts, smoothies, salads, baking',
            ],
            [
                'name' => 'Sun Dried Tomatoes',
                'short_description' => 'Tomatoes dried and packed in oil. Intense flavor, chewy.',
                'calories' => 213,
                'protein' => 5.0,
                'carbs' => 43,
                'sugar' => 37,
                'fiber' => 12,
                'fat' => 2.7,
                'saturated_fat' => 0.4,
                'monounsaturated_fat' => 1.5,
                'polyunsaturated_fat' => 0.8,
                'salt' => 870,
                'vitamins_minerals' => 'Vitamin C, Potassium, Iron, Lycopene',
                'serving_size' => '10g (2–3 pieces)',
                'allergens' => 'May contain sulfite preservatives',
                'common_uses' => 'Salads, pasta, pizza, antipasti, spreads',
            ],
            [
                'name' => 'Tofu',
                'short_description' => 'Soybean curd; plant protein staple.',
                'calories' => 76,
                'protein' => 8,
                'carbs' => 1.9,
                'sugar' => 0.6,
                'fiber' => 0.3,
                'fat' => 4.8,
                'saturated_fat' => 0.7,
                'monounsaturated_fat' => 1.0,
                'polyunsaturated_fat' => 2.7,
                'salt' => 7,
                'vitamins_minerals' => 'Calcium (if set with Ca), Iron, Magnesium',
                'serving_size' => '100g (¼ block)',
                'allergens' => 'Soy',
                'common_uses' => 'Stir-fries, soups, salads, grilling, baking',
            ],
            [
                'name' => 'Tomatoes',
                'short_description' => 'Juicy red fruit, rich in lycopene.',
                'calories' => 18,
                'protein' => 0.9,
                'carbs' => 3.9,
                'sugar' => 2.6,
                'fiber' => 1.2,
                'fat' => 0.2,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 5,
                'vitamins_minerals' => 'Vitamin C, Potassium, Vitamin K, Folate',
                'serving_size' => '100g (~1 medium)',
                'allergens' => 'Rare (oral allergy)',
                'common_uses' => 'Salads, sauces, sandwiches, cooking',
            ],
            [
                'name' => 'Tortilla Stack',
                'short_description' => 'Unleavened wheat flatbread. Mexican staple.',
                'calories' => 306,
                'protein' => 8,
                'carbs' => 50,
                'sugar' => 1.2,
                'fiber' => 3.0,
                'fat' => 7,
                'saturated_fat' => 2,
                'monounsaturated_fat' => 3,
                'polyunsaturated_fat' => 1,
                'salt' => 700,
                'vitamins_minerals' => 'Iron, Calcium, Thiamin (often fortified)',
                'serving_size' => '40g (1 medium tortilla)',
                'allergens' => 'Wheat (gluten)',
                'common_uses' => 'Wraps (burritos, tacos), quesadillas, pinwheels',
            ],
            [
                'name' => 'Tuna Can',
                'short_description' => 'Canned fish in water/brine. Lean protein source.',
                'calories' => 96,
                'protein' => 23,
                'carbs' => 0,
                'sugar' => 0,
                'fiber' => 0,
                'fat' => 0.8,
                'saturated_fat' => 0.2,
                'monounsaturated_fat' => 0.2,
                'polyunsaturated_fat' => 0.2,
                'salt' => 350,
                'vitamins_minerals' => 'Selenium, Vitamin D, B12, Niacin',
                'serving_size' => '56g (half can)',
                'allergens' => 'Fish',
                'common_uses' => 'Salads (tuna salad), sandwiches, pasta, sushi',
            ],
            [
                'name' => 'White Eggs',
                'short_description' => 'Large chicken eggs (white shell). Nutritionally same as brown eggs.',
                'calories' => 143,
                'protein' => 13,
                'carbs' => 0.7,
                'sugar' => 0.4,
                'fiber' => 0,
                'fat' => 10,
                'saturated_fat' => 3.1,
                'monounsaturated_fat' => 3.6,
                'polyunsaturated_fat' => 1.9,
                'salt' => 140,
                'vitamins_minerals' => 'Vitamin B12, D, A, Choline, Selenium',
                'serving_size' => '1 egg (≈50g)',
                'allergens' => 'Egg',
                'common_uses' => 'Boiled, scrambled, omelets, baking, sauces',
            ],
            [
                'name' => 'Zucchini',
                'short_description' => 'Green summer squash with mild flavor. Very low calorie.',
                'calories' => 17,
                'protein' => 1.2,
                'carbs' => 3.1,
                'sugar' => 2.5,
                'fiber' => 1.0,
                'fat' => 0.3,
                'saturated_fat' => 0,
                'monounsaturated_fat' => 0,
                'polyunsaturated_fat' => 0,
                'salt' => 8,
                'vitamins_minerals' => 'Vitamin C, Potassium, Manganese',
                'serving_size' => '100g (½ medium)',
                'allergens' => 'Rare',
                'common_uses' => 'Stir-fries, salads, grilling, baking (ratatouille)',
            ],
    ];

        foreach ($nutritions as $nutr) {
            $product = Product::where('name', $nutr['name'])->first();

            if (!$product) {
                continue;
            }

            ProductNutrition::updateOrCreate(
                ['product_id' => $product->id],
                [
                    'short_description'    => $nutr['short_description'],
                    'calories'             => $nutr['calories'],
                    'protein'              => $nutr['protein'],
                    'carbs'                => $nutr['carbs'],
                    'sugar'                => $nutr['sugar'],
                    'fiber'                => $nutr['fiber'],
                    'fat'                  => $nutr['fat'],
                    'saturated_fat'        => $nutr['saturated_fat'],
                    'monounsaturated_fat'  => $nutr['monounsaturated_fat'],
                    'polyunsaturated_fat'  => $nutr['polyunsaturated_fat'],
                    'salt'                 => $nutr['salt'],
                    'vitamins_minerals'    => $nutr['vitamins_minerals'],
                    'serving_size'         => $nutr['serving_size'],
                    'allergens'            => $nutr['allergens'],
                    'common_uses'          => $nutr['common_uses'],
                ]
            );
        }
    }
}

